
jobs:
  - job: vs2017_cmake_vs_msvc141
    pool:
      vmImage: "vs2017-win2016"
    variables:
      platform: x64
      configuration: Debug
      is_dynamic: True
    steps:
      - template: azure/steps-win-vs.yml
        parameters:
          toolset: v141

  - job: vs2019_cmake_vs_msvc142
    pool:
      vmImage: "windows-2019"
    variables:
      platform: x64
      configuration: Debug
      is_dynamic: True
    steps:
      - template: azure/steps-win-vs.yml
        parameters:
          toolset: v142

  - job: vs2019_cmake_ninja_clang
    pool:
      vmImage: windows-2019
    steps:
      - task: ChocolateyCommand@0
        inputs:
          command: "install"
          installPackageId: "ninja"
          installInstallArgs: "--no-progress --yes"
      - task: ChocolateyCommand@0
        inputs:
          command: "install"
          installPackageId: "llvm"
          installInstallArgs: "--no-progress --yes"
      - task: BatchScript@1
        inputs:
          filename: "./scripts/build-vs2019-cmake-clang.bat"
        env:
          SHARED: True
          BUILD_TYPE: Debug
