
trigger:
  branches:
    exclude:
      - docs
      - gh-pages

strategy:
  maxParallel: 2
  matrix:
    release_x64:
      BuildPlatform: x64
      BuildConfiguration: Release
    debug_x64:
      BuildPlatform: x64
      BuildConfiguration: Debug
    release_x86:
      BuildPlatform: x86
      BuildConfiguration: Release
    debug_x86:
      BuildPlatform: x86
      BuildConfiguration: Debug

variables:
  vcpkg_target_triplet: $(BuildPlatform)-windows

steps:
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        vcpkg install --triplet $(vcpkg_target_triplet) ms-gsl spdlog catch2
        vcpkg list
