#
# Author: github.com/luncliff (luncliff@gmail.com)
# References:
#   https://www.mkdocs.org/
#
site_name: luncliff-media
site_url: https://luncliff.github.io/media

repo_name: luncliff/media
repo_url: https://github.com/luncliff/media

nav:
  - Functions: functions.md

theme: readthedocs

extra:
  social:
    - type: "github"
      link: "https://github.com/luncliff"
